- README.md
- pkg/vehicle/infotainment.go
- Removed `tesla-` in links to Fleet API docs.
- Changed link to partner endpoints to be specifically to the register partner account endpoint.
> fix incorrect Fleet API documentation links

- pkg/cli/config.go
> Fix typo in config.go

- pkg/connector/inet/inet.go
During testing, when sending a command to sleeping vehicles, the call returns a Request Timeout (HTTP 408) with the message "vehicle is offline".  This is not detected as an offline vehicle, and the request will continue to retry in the dispatcher until the context deadline times out, which further obscures the original error.
This change adds to the existing 'offline' handling in inet.go to handle this case.  I have also updated the message to match the existing REST api response text.
> fix vehicle offline detection

- cmd/tesla-http-proxy/main.go
- pkg/cli/config.go
> Cli new config updates

- .github/workflows/build.yml
- Makefile
- add back make format CI step
> test make format ci

- README.md
MacOS uses LibreSSL for the OpenSSL command, and LibreSSL defaults to using explicit curve parameters rather than named curves when encoding private keys with `openssl req ...`. But the Golang x509 library does not support explicit curve parameters, causing `tesla-http-proxy` to fail with "x509: invalid ECDSA parameters".
This commit fixes the problem by adding an option to the openssl command in the README that forces LibreSSL to use named curves.
Fixes #83 
> README: Force use of named curves in example

- internal/dispatcher/dispatcher.go
- internal/dispatcher/dispatcher_test.go
- pkg/connector/ble/ble.go
"Recieve" -> "Receive". D'oh!
The pkg/connector/ble/ble.go method had both Receive and Recieve methods. Deleting the latter is an API-breaking change, but such changes should be expected in v0.x.x according to Go semantic versioning standards.
Fixes #60 
> Spelling fixes

- internal/dispatcher/dispatcher.go
- pkg/proxy/proxy.go
Fixed a race condition that caused the library (and http proxy) to not recognize ErrProtocolNotSupported, which indicates the vehicle does not support the newer protocol.
The race condition was caused by code that attempted to handshake with multiple vehicle subsystems (domains) in parallel. If one subsystem returned ErrProtocolNotSupported, the pending requests to other subsystems were canceled. In some cases, the context cancellation error would be propagated to the down the stack instead of ErrProtocolNotSupported.
With this fix, the library prioritizes non-context cancellation errors.
- [x ] Bug fix (non-breaking change which fixes an issue)
Confirm you have completed …
> Fix race condition in ErrProtocolNotSupported

- internal/dispatcher/dispatcher.go
- internal/dispatcher/dispatcher_test.go
Commit beb8735ec5fa86de1ca60cfee52f1fe784521cfc introduced a regression that prevents clients from establishing session info on connections that are not cached. It caused a handshake to one domain to be cancelled when a handshake to another domain succeeded.
> Fix regression in session info

- cmd/tesla-keygen/main.go
The parameter `-key-file-name` does not exist, and should be `-key-file`. Only a minor change to the console output.
No further references to `key-file-name` exist in the repository.
Fixes #163
> Fix usage of `tesla-keygen migrate`

- pkg/protocol/protocol.md
Updates the protocol documentation to reference the correct Signature Type for HMAC for Command Authorization
If `SIGNATURE_TYPE_HMAC` is used, an `MESSAGEFAULT_ERROR_INVALID_SIGNATURE` is received.
Swapping for `SIGNATURE_TYPE_HMAC_PERSONALIZED` with no other changes causes the commands to be signed correctly and accepted.
> Update "Authorizing commands" section's HMAC Signature type SIGNATURE_TYPE_HMAC_PERSONALIZED

- cmd/tesla-control/commands.go
fix climate-set-temp command wrong conversion equation
- Previously, sending a climate-set-temp command in "f or F" units set the cabin temp to HIGH. 
- Only "c or C" units were accepted Now command sets cabin to appropriate temperature in both units.
> tesla-control: fix climate-set-temp command wrong conversion equation

- cmd/tesla-control/commands.go
- pkg/proxy/command.go
- pkg/proxy/proxy.go
Adds window controls to http proxy and CLI.
Fixes bug where errors were not being propagated by the http proxy.
Fixes #210
> Tesla control windows

- cmd/tesla-control/commands.go
- pkg/vehicle/security.go
- pkg/vehicle/vcsec.go
Previously, the API only allowed adding keys with the Owner or Driver roles. This expands the API to allow keys with other roles. See pkg/protocol/protocol.md for documentation on the different roles.
Fixes #217 
> Support adding keys with different roles

- README.md
- pkg/connector/inet/inet.go
Fast fail on 429 errors to give clients better control over retry policies.
Document TESLA_CACHE_FILE environment variable, which may help clients avoid 429s to begin with.
Fixes #238 
> Fast fail 429

- pkg/connector/ble/device_darwin.go
- pkg/connector/ble/device_linux.go
In the file `pkg/connector/ble/ble.go` there is a check for `device != nil`, however this can be false even though the previous call failed to init the ble device. 
The reason is that the `Device` is an interface and for interface to be `nil` it needs to have both value and a type nil, see
https://go.dev/doc/faq#nil_error
> device: return nil device on error

- pkg/account/account_test.go
1. **Table-Driven Tests**: Refactored `TestNewAccount` to use table-driven tests, reducing redundancy and improving readability.
2. **Consistent Error Messages**: Standardized error messages for clarity.
3. **Function Comments**: Added comments to functions for better understanding.
4. **Expected Results Checks**: Improved assertions to check for expected results clearly.
5. **Named Test Cases**: Used `t.Run` for named sub-tests, making it easier to identify specific failing cases.
> Refactor TestNewAccount with Table-Driven Tests and Enhance Readability

- cmd/tesla-control/commands.go
- pkg/proxy/command.go
- pkg/vehicle/security.go
Erases user's data from the user interface. Requires the vehicle to be parked and in Guest Mode.
> Add erase-guest-data command

- cmd/tesla-control/commands.go
- pkg/connector/ble/ble.go
- pkg/connector/ble/device_linux.go
Improve BLE connection reliability:
- Increase timeouts for BLE dialer and listener
- Retry initial connection on non-fatal errors until context expires
- Tweak scanning interval to reflect BLE advertisement parameters
Future improvements (deferred to get the existing improvements merged sooner):
- Retry connection using client MAC address instead of scanning
- Optimize scanning interval
- Adjust timeouts using caller context
Fixes #253 
> Improve BLE reliability

- cmd/tesla-jws/main.go
- go.mod
- go.sum
- internal/authentication/jwt.go
- internal/authentication/jwt_test.go
- pkg/proxy/proxy.go
Upgrade `github.com/golang-jwt/jwt` to `github.com/golang-jwt/jwt/v5`.
[Migration guide used](https://github.com/golang-jwt/jwt/blob/v5.2.1/MIGRATION_GUIDE.md).
To test, I configured a vehicle for fleet-telemetry using the http proxy.
Fixes #294 
> upgrade to golang-jwt/jwt v5

- .dockerignore
- .github/workflows/publish.yml
- .gitignore
- Dockerfile
- README.md
- cmd/tesla-control/main.go
- cmd/tesla-http-proxy/main.go
- cmd/tesla-http-proxy/main_test.go
- docker-compose.yml
Adding a `Dockerfile` to make it easier to run the tools provided. This will be most useful for those wishing to run the HTTP proxy in a production environment.
This introduces environment variable support for all flags available on the HTTP proxy. Environment variables are more graceful to use than command line flags when working with Docker.
I've done manual end to end testing, but would appreciate someone else setting this up themselves to help validate.
Fixes #225 
> add docker support

- cmd/tesla-keygen/main.go
- Introduced the `-output` flag to allow users to specify a file path for saving the public key.
- Updated the `printPublicKey` function to write the public key to the specified file, or to stdout if no file is provided.
- Modified the `create` and `migrate` cases to support the `-output` flag when printing the public key.
- Ensured backward compatibility by retaining stdout output when `-output` is not used.
> feat: add support for saving public key to file using -output flag

- pkg/connector/ble/device_windows.go
Fixes show-stopper build on Windows:
```raw
> go build ./...
..\..\pkg\connector\ble\ble.go:161:17: undefined: newDevice
```
Even if not supported for BLE, building on Windows is still possible for other targets like the `tesla-http-proxy`. With the proposed basic change the build is unblocked.
Invoking commands that involves BLE will be correctly report the runtime error:
```raw
> tesla-control -ble add-key-request public_key.pem owner cloud_key
Error: failed to find a BLE device: Not supported on Windows
```
> - Fixed build on Windows

- pkg/account/account.go
- pkg/account/account_test.go
- pkg/connector/inet/inet.go
- pkg/proxy/proxy.go
currently vehicle command will retry commands if tesla host return 421. We want to share the same behavior for other proxied request as well.
> retry for other region

- pkg/proxy/proxy.go
fix body not properly populated issue for https://github.com/teslamotors/vehicle-command/pull/315
> fix proxy retry body

- Dockerfile
Similar to https://github.com/teslamotors/fleet-telemetry/pull/224, there should be no need to run the docker image as root
> Use non root image

- cmd/tesla-control/commands.go
- pkg/vehicle/security.go
- pkg/vehicle/security_test.go
Adds valet mode commands to the tesla-control CLI tool. These commands were already supported in the library and HTTP proxy.
> tesla-control: enable/disable valet mode

- pkg/cli/config.go
A session cache can reduce the number of Fleet API calls made by clients, but needed to be explicitly enabled by the user. With this change, the cache will be enabled by default and saved to ~/.tesla-cache.json. This path can be overridden using the `-session-cache` command-line flag or by setting TESLA_CACHE_FILE, as before.
Users can add the `-disable-session-cache` command-line flag to disable the feature.
> Enable session cache by default

- .golangci.yml
- internal/dispatcher/dispatcher.go
- internal/dispatcher/session.go
- pkg/proxy/command.go
Linter fixes
- [] Documentation update
> Fix static and non-exported return linters

- go.mod
- go.sum
- pkg/connector/ble/ble.go
This PR splits the `ble.tryToConnect` method in to two parts, by factoring out its first step in which we scan for a suitable tesla BLE advertisement (beacon). This is achieved by putting the code in a new `ble.scanVehicleBeacon` method along with other smaller refactorings. This allows us to expose the new method with `ble.ScanVehicleBeacon`.
The end user can then use a different (shorter) timeout to check for the presence of the vehicle before deciding if it wants to try to connect, since if a beacon got detected it would make sense to use a longer timeout to connect, or even do multiple retries, and if it wasn't detected allow for faster error handling.
Example
```go
// Old way
conn, err := ble.NewConnection(ctx, vin)
// New way
// Either try to connect immediatly
conn, err := …
```
> Refactor BLE connecting to allow scanning for vehicle presence

- cmd/tesla-jws/main.go
- internal/authentication/jwt.go
- pkg/proxy/proxy.go
- pkg/sign/doc.go
- pkg/sign/sign.go
- refactor: create new public package sign
- refactor: move the func SignMessageForVehicle & SignMessageForFleet from internal/authentication to pkg/sign
Fixes #377 
> Feat export funcs SignMessageForVehicle & SignMessageForFleet

- cmd/tesla-control/commands.go
- Fixes issue where precondition schedules were not being removed correctly due to incorrect function call to RemoveChargeSchedule.
- Add missing requiresAuth and requiresFleetAPI flag on autosecure-modelx and flash-lights command.
> Fix Precondition schedule removal logic and add missing flags

- go.mod
- go.sum
Not sure if this sort of patch is welcome, but 5.2.2 fixes an unrelated CVE, and it's simpler for us to update the module than argue/confirm why this vulnerability doesn't affect this repo. Figured I'd submit an upstream patch while I was at it.
Also includes a small fix to ensure go toolchain magic works properly. See https://github.com/golang/go/issues/65568#issuecomment-1954876836 for more details.
See https://github.com/advisories/GHSA-mh63-6h87-95cp golang-jwt 5.2.2 release notes: https://github.com/golang-jwt/jwt/releases/tag/v5.2.2
> Update golang-jwt module to 5.2.2

- README.md
Some common tools reportedly do not support NIST P521 TLS suites.
We avoid using P256 here to reduce the chance that someone will re-use the P256 command-signing key as a TLS key.
Fixes #398.
> Change example TLS key from P521 to P384
